import {
  faCalendarCheck,
  faCameraRetro,
  faCheck,
  faChevronDown,
  faClipboardList,
  faEye,
  faFileUpload,
  faFolderPlus,
  faFolderTree,
  faHeart,
  faIcons,
  faMagnifyingGlass,
  faNewspaper,
  faPenFancy,
  faPenToSquare,
  faPersonBiking,
  faPersonHiking,
  faPhotoFilm,
  faPlaneDeparture,
  faPlus,
  faRectangleList,
  faSliders,
  faSquarePlus,
  faSuitcaseRolling,
  faThumbsUp,
  faTrashCan,
  faUpRightFromSquare,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';

export const SfIcons = {
  add: faPlus,
  addForm: faFolderPlus,
  addMedia: faSquarePlus,
  allForms: faRectangleList,
  backgroundImage: faCameraRetro,
  bikeTrip: faPersonBiking,
  cancel: faXmark,
  classicTrip: faPersonHiking,
  delete: faTrashCan,
  dropDownArrow: faChevronDown,
  editQuestion: faPenFancy,
  forms: faFolderTree,
  media: faPhotoFilm,
  mediaLibrary: faIcons,
  linkTo: faUpRightFromSquare,
  photoRel: faCameraRetro,
  post: faPenToSquare,
  postOptions: faSliders,
  posts: faNewspaper,
  recommendations: faHeart,
  save: faCheck,
  search: faMagnifyingGlass,
  surveyAdd: faClipboardList,
  surveyPreview: faEye,
  tips: faThumbsUp,
  tripDetails: faSuitcaseRolling,
  trips: faPlaneDeparture,
  upload: faFileUpload,
  weekendTrip: faCalendarCheck,
};
