import {
  faCalendarCheck,
  faCameraRetro,
  faChevronDown,
  faFileUpload,
  faFolderPlus,
  faFolderTree,
  faHeart,
  faIcons,
  faMagnifyingGlass,
  faNewspaper,
  faPersonBiking,
  faPersonHiking,
  faPhotoFilm,
  faPlaneDeparture,
  faPlus,
  faRectangleList,
  faSquarePlus,
  faThumbsUp,
  faTrashCan
} from '@fortawesome/free-solid-svg-icons';

export const SfIcons = {
  add: faPlus,
  addForm: faFolderPlus,
  addMedia: faSquarePlus,
  allForms: faRectangleList,
  bikeTrip: faPersonBiking,
  classicTrip: faPersonHiking,
  delete: faTrashCan,
  dropDownArrow: faChevronDown,
  forms: faFolderTree,
  media: faPhotoFilm,
  mediaLibrary: faIcons,
  photoRel: faCameraRetro,
  posts: faNewspaper,
  recommendations: faHeart,
  search: faMagnifyingGlass,
  tips: faThumbsUp,
  trips: faPlaneDeparture,
  upload: faFileUpload,
  weekendTrip: faCalendarCheck,
}
